### ISSUE TITLE
Date Obs Column Name Change

### ISSUE THREAD

**Issue by hannahc243** [samaloney/stixpy#30]
Quicklook files downloaded seem to now have the header column name 'date-obs' instead of previously 'date_obs' and so when trying to run quicklook.py, reach an error on line 165:  data['time'] = Time(header['date_obs']) + TimeDelta(data['time'] * u.s) .. maybe it should be changed to: Time(header['date-obs']) + ... Does this relate to issue #29 ?

**Comment by samaloney** [comment]
Closed in #35
