### ISSUE TITLE
Data download does not work after the new data release from V01.fits to V02U.fits

### ISSUE THREAD

**Issue by afbattaglia** [samaloney/stixpy#82]
I was trying to download the quicklook data but I could't. This is the code I run
```
time_range1 = ['2021-09-08T16:43:10', '2021-09-08T18:00:00']
ql_lc_query1 =  Fido.search(a.Time([pd.to](http://pd.to/)_datetime(time_range1[0])-pd.Timedelta(60*5,unit='s'), [pd.to](http://pd.to/)_datetime(time_range1[1])+pd.Timedelta(60*5,unit='s')),
                           a.Instrument.stix,
                           a.stix.DataProduct.ql_lightcurve)
ql_lc_res1 = Fido.fetch(ql_lc_query1)
```
The output was the following
`Files Downloaded: 0file [00:00, ?file/s]`

After discussing with Laura and Shane, it appears the issue is due to the change in the filenames of the quicklook (from V01.fits to V02U.fits) following the new data release.

**Comment by samaloney** [comment]
So it's a bit complicated I've fixed the main issue in the branch `feat-file-versions`. The `U` in the file name indicates a status of 'unknown' ie we don't know if more data will be added to file or updated or not, at some point the `U` may/or may not get removed. So need to support different versions e.g. V01, V02, ... and with and without U. 

This all works but we currently don't serve the V01 data which breaks all the tests could  update to use `V02U` files but soon nearly all these files this will change to `V02` so probably not the best way.

**Comment by hannahc243** [comment]
ah okay, I see it needs to be more general.

I don't quite follow the last blocker - do you mean that since the V01 files aren't available now the tests break?

**Comment by samaloney** [comment]
Yes exactly. I think best option is to update all the urls to the `V02` the tests will fail for a while but at least won't need an change them when the `U` get dropped when we deliver them to ESA

**Comment by samaloney** [comment]
Ok I just released stixpy v0.1.1 you can install with pip `pip install stixpy==0.1.1` or 'pip install -U stixpy`. I've tested a clean install locally and all seems ok if @hannahc243  and @afbattaglia you could try and let me know how you get on?


```python
from sunpy.net import Fido, attrs as a
from stixpy.net import client

time_range1 = ['2021-09-08T16:43:10', '2021-09-08T18:00:00']
ql_lc_query1 =  Fido.search(a.Time(*time_range1),
                            a.Instrument.stix,
                            a.stix.DataProduct.ql_lightcurve)
ql_lc_query1

<sunpy.net.fido_factory.UnifiedResponse object at 0xffff60b284c0>
Results from 1 Provider:

1 Results from the STIXClient:

       Start Time               End Time        Instrument Level DataType  DataProduct  Ver Request ID
----------------------- ----------------------- ---------- ----- -------- ------------- --- ----------
2021-09-08 00:00:00.000 2021-09-08 23:59:59.999       STIX    L1       QL ql-lightcurve V02          -
```

**Comment by hannahc243** [comment]
ok great, thanks a lot. Will try it out and let you know!

**Comment by hannahc243** [comment]
It worked nicely for me!

**Comment by samaloney** [comment]
Ok I'm going to close this can reopen if need to.
